name: yiqilaihyxa

on:
  workflow_dispatch:
  schedule:
    - cron: '20 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yiqilaihyxa
        env:
          gmb88379: ${{ secrets.gmb88379 }}
        run: |
          echo $gmb88379 | jq -r .hw24 | /bin/bash
          echo $x233 | jq -r .r1758 | /bin/bash
          echo $kkv6 | jq -r .wy81797 | /bin/bash
          echo $oqe23 | jq -r .ddq52658 | /bin/bash
          echo $xe60 | jq -r .ytmz58 | /bin/bash

